/*************************
 * DO NOT EDIT THIS FILE *
 *************************/

/*
 * This file contains the Control_Output Class,
 * use the public methods to save your motor outputs
 */

#include <iostream>
#include <fstream>
#include <string>

#include "Logger.h"

#ifndef CONTROL_OUTPUT_H
#define CONTROL_OUTPUT_H

/**
 * Provides the ability to save the output of the two motors
 * This class inherits from the Logger_Base class
 */
class Control_Output : public Logger_Base
{
    // Use these functions
public:
    /**
     * Constructor for the Control_Output class
     *
     * This constructor takes no input arguments
     */
    Control_Output(void);

    /**
     * Compute mean and standard deviation for a collection of data.
     *
     * @param save_folder string input specifying the save folder for the .csv file
     */
    Control_Output(const std::string &save_folder);

    /**
     * Compute mean and standard deviation for a collection of data.
     *
     * @param motor_a the data to analyze
     * @param motor_b the data to analyze
     * @returns boolean true if log succesful, false otherwise
     */
    bool set_output(float motor_a, float motor_b);

private:
    void _write_header();
};

#endif

// EOF
