/*************************
 * DO NOT EDIT THIS FILE *
 *************************/
#include <ctime>
#include <chrono>
#include <string>

#include "Control_Output.h"

Control_Output::Control_Output(void) : Control_Output(".") {}

Control_Output::Control_Output(const std::string &save_folder) : Logger_Base("motor", save_folder)
{
    _init();
}

bool Control_Output::set_output(float motor_a, float motor_b)
{
    if (_mFile.is_open())
    {
        _mFile << _mLine_num << ", " << motor_a << ", " << motor_b << std::endl;
        _mLine_num++;
        return true;
    }
    else
    {
        std::cout << "Output file not open" << std::endl;
        return false;
    }
}

void Control_Output::_write_header()
{
    if (_mFile.is_open())
    {
        _mFile << _log_name << std::endl;
        _mFile << "----------------" << std::endl;
        _mFile << "line no"
               << ", "
               << "motor a"
               << ", "
               << "motor b" << std::endl;
    }
    else
        std::cout << "Control_Output: could not write log, log file not open" << std::endl;
}

// EOF

